import { Category, DeliveryPlatform, DiningTable, MenuItem, Order, User, SystemSettings } from '@/types';

export const INITIAL_USERS: User[] = [
  { User_id: 502, User_name: 'vu', User_password: '111', Full_name: 'Vũ (Quản Lý)', Role: 'ADMIN', Phone: '0901234567' },
  { User_id: 503, User_name: 'admin', User_password: '123456', Full_name: 'Admin Hệ Thống', Role: 'ADMIN', Phone: '0901112233' },
  { User_id: 209, User_name: 'quay', User_password: '111', Full_name: 'Thu Ngân Quầy', Role: 'CASHIER', Phone: '0908888888' },
  { User_id: 504, User_name: 'cashier1', User_password: '123456', Full_name: 'Thu Ngân Ca Tối', Role: 'CASHIER', Phone: '0903334455' },
  { User_id: 505, User_name: 'boi', User_password: '111', Full_name: 'Bồi Bàn', Role: 'WAITER', Phone: '0909999999' },
  { User_id: 289, User_name: 'bep', User_password: '111', Full_name: 'Bếp Hoa Sen', Role: 'KITCHEN', Phone: '0907654321' },
];

export const INITIAL_CATEGORIES: Category[] = [
  { Category_id: 1, Category_name: 'Món Điểm Tâm & Bún/Phở', Display_order: 1, Is_active: 1 },
  { Category_id: 2, Category_name: 'Món Khai Vị & Gỏi', Display_order: 2, Is_active: 1 },
  { Category_id: 3, Category_name: 'Món Cơm & Cơm Chiên', Display_order: 3, Is_active: 1 },
  { Category_id: 4, Category_name: 'Món Lẩu Chay Thanh Đạm', Display_order: 4, Is_active: 1 },
  { Category_id: 5, Category_name: 'Món Kho & Xào Mặn', Display_order: 5, Is_active: 1 },
  { Category_id: 6, Category_name: 'Món Canh & Lẩu Cốc', Display_order: 6, Is_active: 1 },
  { Category_id: 7, Category_name: 'Món Chiên & Rán Giòn', Display_order: 7, Is_active: 1 },
  { Category_id: 8, Category_name: 'Món Hấp & Luộc Thanh Tịnh', Display_order: 8, Is_active: 1 },
  { Category_id: 9, Category_name: 'Tráng Miệng & Chè Chay', Display_order: 9, Is_active: 1 },
  { Category_id: 10, Category_name: 'Nước Uống & Trà Thảo Mộc', Display_order: 10, Is_active: 1 },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Danh mục 1: Bún / Phở
  {
    Item_id: 101,
    Category_id: 1,
    Item_code: 'DT001',
    Item_name: 'Phở Chay Hoa Sen',
    Base_price: 45000,
    Image_url: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=500',
    Description: 'Nước dùng ninh từ củ quả ngọt thanh tự nhiên',
    Is_available: 1,
  },
  {
    Item_id: 102,
    Category_id: 1,
    Item_code: 'DT002',
    Item_name: 'Bún Huế Chay',
    Base_price: 45000,
    Image_url: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=500',
    Description: 'Đậm đà vị sa tế chay và nấm đông cô',
    Is_available: 1,
  },
  {
    Item_id: 103,
    Category_id: 1,
    Item_code: 'DT003',
    Item_name: 'Bún Riêu Chay',
    Base_price: 40000,
    Image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500',
    Description: 'Riêu làm từ đậu hũ non và váng đậu thơm béo',
    Is_available: 1,
  },
  {
    Item_id: 104,
    Category_id: 1,
    Item_code: 'DT004',
    Item_name: 'Hủ Tiếu Nam Vang Chay',
    Base_price: 45000,
    Image_url: 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=500',
    Description: 'Hủ tiếu dai ngon tô điểm nấm bào ngư và chả lụa chay',
    Is_available: 1,
  },
  {
    Item_id: 105,
    Category_id: 1,
    Item_code: 'DT005',
    Item_name: 'Bánh Canh Nấm Chay',
    Base_price: 40000,
    Image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500',
    Description: 'Nước dùng sánh béo thơm mùi hành boaro nấm rơm',
    Is_available: 1,
  },

  // Danh mục 2: Khai vị & Gỏi
  {
    Item_id: 201,
    Category_id: 2,
    Item_code: 'KV001',
    Item_name: 'Gỏi Ngó Sen Tôm Chay',
    Base_price: 65000,
    Image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500',
    Description: 'Ngó sen giòn ngọt, tôm chay và đậu phộng rang giòn',
    Is_available: 1,
  },
  {
    Item_id: 202,
    Category_id: 2,
    Item_code: 'KV002',
    Item_name: 'Gỏi Củ Hủ Dừa Chay',
    Base_price: 70000,
    Image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
    Description: 'Đặc sản miền tây thanh ngọt mát lành',
    Is_available: 1,
  },
  {
    Item_id: 203,
    Category_id: 2,
    Item_code: 'KV003',
    Item_name: 'Chả Giò Hoa Sen Giòn',
    Base_price: 55000,
    Image_url: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=500',
    Description: 'Nhân khoai môn nấm đông cô giòn rụm',
    Is_available: 1,
  },

  // Danh mục 3: Cơm Chiên
  {
    Item_id: 301,
    Category_id: 3,
    Item_code: 'C001',
    Item_name: 'Cơm Chiên Dương Châu Chay',
    Base_price: 50000,
    Image_url: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500',
    Description: 'Hạt cơm vàng óng kèm ngũ sắc rau củ tươi ngon',
    Is_available: 1,
  },
  {
    Item_id: 302,
    Category_id: 3,
    Item_code: 'C002',
    Item_name: 'Cơm Chiên Hạt Sen Hoa Sen',
    Base_price: 60000,
    Image_url: 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=500',
    Description: 'Cơm gói lá sen thơm lừng mùi thảo mộc thiên nhiên',
    Is_available: 1,
  },
  {
    Item_id: 303,
    Category_id: 3,
    Item_code: 'C003',
    Item_name: 'Cơm Chiên Sốt Khóm (Dứa)',
    Base_price: 65000,
    Image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500',
    Description: 'Phục vụ trong trái dứa thơm chua ngọt hài hòa',
    Is_available: 1,
  },

  // Danh mục 4: Lẩu Chay
  {
    Item_id: 401,
    Category_id: 4,
    Item_code: 'L001',
    Item_name: 'Lẩu Nấm Thần Tiên Hoa Sen',
    Base_price: 199000,
    Image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500',
    Description: 'Mười loại nấm quý thanh lọc bồi bổ cơ thể',
    Is_available: 1,
  },
  {
    Item_id: 402,
    Category_id: 4,
    Item_code: 'L002',
    Item_name: 'Lẩu Thái Chua Cay Chay',
    Base_price: 189000,
    Image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500',
    Description: 'Nước lẩu thơm vị sả tắc lá chúc và ớt chưng',
    Is_available: 1,
  },

  // Danh mục 5: Kho & Xào
  {
    Item_id: 501,
    Category_id: 5,
    Item_code: 'KX001',
    Item_name: 'Nấm Rơm Kho Quẹt',
    Base_price: 65000,
    Image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500',
    Description: 'Ăn kèm rau luộc thập cẩm giòn ngọt',
    Is_available: 1,
  },
  {
    Item_id: 502,
    Category_id: 5,
    Item_code: 'KX002',
    Item_name: 'Đậu Hũ Kho Nấm Tiêu Xanh',
    Base_price: 55000,
    Image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500',
    Description: 'Đậu hũ chiên vàng thấm vị sốt tiêu đen cay nhẹ',
    Is_available: 1,
  },

  // Danh mục 6: Canh
  {
    Item_id: 601,
    Category_id: 6,
    Item_code: 'CN001',
    Item_name: 'Canh Chua Chay Nam Bộ',
    Base_price: 50000,
    Image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500',
    Description: 'Nấu me chua đậu bắp giá đậu và rau om',
    Is_available: 1,
  },
  {
    Item_id: 602,
    Category_id: 6,
    Item_code: 'CN002',
    Item_name: 'Canh Rong Biển Đậu Hũ',
    Base_price: 45000,
    Image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500',
    Description: 'Thanh mát bổ dưỡng phong cách thực dưỡng',
    Is_available: 1,
  },

  // Danh mục 7: Chiên Rán
  {
    Item_id: 701,
    Category_id: 7,
    Item_code: 'CH001',
    Item_name: 'Đậu Hũ Lướt Ván Sả Ớt',
    Base_price: 45000,
    Image_url: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=500',
    Description: 'Bên ngoài giòn vàng ruộm, bên trong mềm mịn',
    Is_available: 1,
  },
  {
    Item_id: 702,
    Category_id: 7,
    Item_code: 'CH002',
    Item_name: 'Nấm Kim Chiên Xù Giòn',
    Base_price: 50000,
    Image_url: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=500',
    Description: 'Giòn rụm chấm kèm sốt tương xí muội béo chua ngọt',
    Is_available: 1,
  },

  // Danh mục 8: Hấp Luộc
  {
    Item_id: 801,
    Category_id: 8,
    Item_code: 'H001',
    Item_name: 'Rau Luộc Thập Cẩm Kho Quẹt',
    Base_price: 55000,
    Image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500',
    Description: 'Bầu, củ cải, đậu que, bắp cải hấp ngọt lành',
    Is_available: 1,
  },
  {
    Item_id: 802,
    Category_id: 8,
    Item_code: 'H002',
    Item_name: 'Đậu Hũ Non Hấp Hồng Kông',
    Base_price: 55000,
    Image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
    Description: 'Sốt xì dầu thơm boaro và gừng sợi thanh dịu',
    Is_available: 1,
  },

  // Danh mục 9: Tráng miệng
  {
    Item_id: 901,
    Category_id: 9,
    Item_code: 'TM001',
    Item_name: 'Chè Bưởi An Giang Cốt Dừa',
    Base_price: 25000,
    Image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500',
    Description: 'Cùi bưởi giòn sần sật béo ngậy nước cốt dừa',
    Is_available: 1,
  },
  {
    Item_id: 902,
    Category_id: 9,
    Item_code: 'TM002',
    Item_name: 'Chè Hạt Sen Long Nhãn',
    Base_price: 30000,
    Image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500',
    Description: 'Thanh mát an thần dễ ngủ, hạt sen bùi bùi',
    Is_available: 1,
  },

  // Danh mục 10: Nước uống
  {
    Item_id: 1001,
    Category_id: 10,
    Item_code: 'NU001',
    Item_name: 'Trà Sen Vàng Kem Béo',
    Base_price: 35000,
    Image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500',
    Description: 'Trà thanh dịu váng kem sữa tươi củ sen giòn',
    Is_available: 1,
  },
  {
    Item_id: 1002,
    Category_id: 10,
    Item_code: 'NU002',
    Item_name: 'Trà Đào Sả Tắc Mát Lạnh',
    Base_price: 30000,
    Image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500',
    Description: 'Đào miếng giòn sảng khoái với hương sả tắc',
    Is_available: 1,
  },
];

export const INITIAL_TABLES: DiningTable[] = [
  // Tầng 1
  { Table_id: 1, Table_code: 'B01', Table_name: 'Bàn 01', Area: 'Tầng 1', Capacity: 4, Current_guests: 0, Status: 'EMPTY', Current_amount: 0, Payment_status: 'UNPAID', Sort_order: 1 },
  { Table_id: 2, Table_code: 'B02', Table_name: 'Bàn 02', Area: 'Tầng 1', Capacity: 4, Current_guests: 0, Status: 'EMPTY', Current_amount: 0, Payment_status: 'UNPAID', Sort_order: 2 },
  { Table_id: 3, Table_code: 'B03', Table_name: 'Bàn 03', Area: 'Tầng 1', Capacity: 2, Current_guests: 0, Status: 'EMPTY', Current_amount: 0, Payment_status: 'UNPAID', Sort_order: 3 },
  { Table_id: 4, Table_code: 'B04', Table_name: 'Bàn 04', Area: 'Tầng 1', Capacity: 6, Current_guests: 4, Status: 'SERVING', Current_order_id: 101, Current_order_code: 'CHAY-882190', Current_amount: 215000, Payment_status: 'UNPAID', Sort_order: 4 },
  { Table_id: 5, Table_code: 'B05', Table_name: 'Bàn 05', Area: 'Tầng 1', Capacity: 4, Current_guests: 0, Status: 'EMPTY', Current_amount: 0, Payment_status: 'UNPAID', Sort_order: 5 },
  { Table_id: 6, Table_code: 'B06', Table_name: 'Bàn 06', Area: 'Tầng 1', Capacity: 8, Current_guests: 0, Status: 'EMPTY', Current_amount: 0, Payment_status: 'UNPAID', Sort_order: 6 },

  // Tầng 2
  { Table_id: 7, Table_code: 'B07', Table_name: 'Bàn 07', Area: 'Tầng 2', Capacity: 4, Current_guests: 0, Status: 'EMPTY', Current_amount: 0, Payment_status: 'UNPAID', Sort_order: 7 },
  { Table_id: 8, Table_code: 'B08', Table_name: 'Bàn 08', Area: 'Tầng 2', Capacity: 4, Current_guests: 2, Status: 'SERVING', Current_order_id: 102, Current_order_code: 'CHAY-901452', Current_amount: 145000, Payment_status: 'UNPAID', Sort_order: 8 },
  { Table_id: 9, Table_code: 'B09', Table_name: 'Bàn 09', Area: 'Tầng 2', Capacity: 6, Current_guests: 0, Status: 'EMPTY', Current_amount: 0, Payment_status: 'UNPAID', Sort_order: 9 },
  { Table_id: 10, Table_code: 'B10', Table_name: 'Bàn 10', Area: 'Tầng 2', Capacity: 4, Current_guests: 0, Status: 'EMPTY', Current_amount: 0, Payment_status: 'UNPAID', Sort_order: 10 },

  // Sân Vườn
  { Table_id: 11, Table_code: 'SV01', Table_name: 'Bàn SV 01', Area: 'Sân Vườn', Capacity: 4, Current_guests: 3, Status: 'SERVING', Current_order_id: 103, Current_order_code: 'CHAY-349021', Current_amount: 195000, Payment_status: 'UNPAID', Sort_order: 11 },
  { Table_id: 12, Table_code: 'SV02', Table_name: 'Bàn SV 02', Area: 'Sân Vườn', Capacity: 6, Current_guests: 0, Status: 'EMPTY', Current_amount: 0, Payment_status: 'UNPAID', Sort_order: 12 },

  // Phòng VIP
  { Table_id: 13, Table_code: 'VIP01', Table_name: 'Phòng VIP 1', Area: 'Phòng VIP', Capacity: 10, Current_guests: 0, Status: 'EMPTY', Current_amount: 0, Payment_status: 'UNPAID', Sort_order: 13 },
  { Table_id: 14, Table_code: 'VIP02', Table_name: 'Phòng VIP 2', Area: 'Phòng VIP', Capacity: 12, Current_guests: 8, Status: 'SERVING', Current_order_id: 104, Current_order_code: 'CHAY-772910', Current_amount: 490000, Payment_status: 'UNPAID', Sort_order: 14 },
];

export const INITIAL_PLATFORMS: DeliveryPlatform[] = [
  { Platform_id: 1, Platform_name: 'GrabFood', Platform_code: 'GRABFOOD', Fee_percentage: 20, Icon_class: 'motorcycle', Color_code: '#00b14f', Is_active: 1, Sort_order: 1 },
  { Platform_id: 2, Platform_name: 'ShopeeFood', Platform_code: 'SHOPEEFOOD', Fee_percentage: 20, Icon_class: 'shopping-bag', Color_code: '#ee4d2d', Is_active: 1, Sort_order: 2 },
  { Platform_id: 3, Platform_name: 'BeFood', Platform_code: 'BEFOOD', Fee_percentage: 20, Icon_class: 'motorcycle', Color_code: '#ffcc00', Is_active: 1, Sort_order: 3 },
  { Platform_id: 4, Platform_name: 'Hotline Quán', Platform_code: 'HOTLINE', Fee_percentage: 0, Icon_class: 'phone', Color_code: '#2e7d32', Is_active: 1, Sort_order: 4 },
  { Platform_id: 5, Platform_name: 'Khách Lấy (Mang Về)', Platform_code: 'TAKEAWAY', Fee_percentage: 0, Icon_class: 'archive', Color_code: '#0288d1', Is_active: 1, Sort_order: 5 },
];

export const INITIAL_ORDERS: Order[] = [
  {
    Order_id: 101,
    Order_code: 'CHAY-882190',
    Table_id: 4,
    Table_name: 'Bàn 04',
    Table_number: 'B04',
    Guest_count: 4,
    Total_amount: 215000,
    Final_amount: 215000,
    Status: 'COOKING',
    Payment_status: 'UNPAID',
    Payment_type: 'CASH',
    Staff_name: 'Vũ (Quản Lý)',
    Created_at: new Date(Date.now() - 12 * 60000).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }),
    items: [
      { Item_id: 101, Item_name: 'Phở Chay Hoa Sen', Quantity: 2, Price: 45000, Total: 90000, Note: 'Ít ớt, nhiều ngò', Status: 'COOKING' },
      { Item_id: 203, Item_name: 'Chả Giò Hoa Sen Giòn', Quantity: 1, Price: 55000, Total: 55000, Note: 'Chiên giòn', Status: 'COOKING' },
      { Item_id: 1001, Item_name: 'Trà Sen Vàng Kem Béo', Quantity: 2, Price: 35000, Total: 70000, Note: 'Ít đường', Status: 'READY' },
    ],
  },
  {
    Order_id: 102,
    Order_code: 'CHAY-901452',
    Table_id: 8,
    Table_name: 'Bàn 08',
    Table_number: 'B08',
    Guest_count: 2,
    Total_amount: 145000,
    Final_amount: 145000,
    Status: 'PROCESSING',
    Payment_status: 'UNPAID',
    Payment_type: 'CASH',
    Staff_name: 'Bồi Bàn',
    Created_at: new Date(Date.now() - 5 * 60000).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }),
    items: [
      { Item_id: 302, Item_name: 'Cơm Chiên Hạt Sen Hoa Sen', Quantity: 1, Price: 60000, Total: 60000, Status: 'PENDING' },
      { Item_id: 201, Item_name: 'Gỏi Ngó Sen Tôm Chay', Quantity: 1, Price: 65000, Total: 65000, Status: 'PENDING' },
      { Item_id: 901, Item_name: 'Chè Bưởi An Giang Cốt Dừa', Quantity: 1, Price: 25000, Total: 25000, Status: 'PENDING' },
    ],
  },
  {
    Order_id: 103,
    Order_code: 'CHAY-349021',
    Table_id: 11,
    Table_name: 'Bàn SV 01',
    Table_number: 'SV01',
    Guest_count: 3,
    Total_amount: 195000,
    Final_amount: 195000,
    Status: 'READY',
    Payment_status: 'UNPAID',
    Payment_type: 'TRANSFER',
    Staff_name: 'Thu Ngân Quầy',
    Created_at: new Date(Date.now() - 18 * 60000).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }),
    items: [
      { Item_id: 402, Item_name: 'Lẩu Thái Chua Cay Chay', Quantity: 1, Price: 189000, Total: 189000, Status: 'READY' },
      { Item_id: 1002, Item_name: 'Trà Đào Sả Tắc Mát Lạnh', Quantity: 2, Price: 30000, Total: 60000, Status: 'READY' },
    ],
  },
  {
    Order_id: 104,
    Order_code: 'CHAY-772910',
    Table_id: 14,
    Table_name: 'Phòng VIP 2',
    Table_number: 'VIP02',
    Guest_count: 8,
    Total_amount: 490000,
    Final_amount: 490000,
    Status: 'COOKING',
    Payment_status: 'UNPAID',
    Payment_type: 'TRANSFER',
    Staff_name: 'Vũ (Quản Lý)',
    Created_at: new Date(Date.now() - 25 * 60000).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }),
    items: [
      { Item_id: 401, Item_name: 'Lẩu Nấm Thần Tiên Hoa Sen', Quantity: 2, Price: 199000, Total: 398000, Status: 'COOKING' },
      { Item_id: 201, Item_name: 'Gỏi Ngó Sen Tôm Chay', Quantity: 1, Price: 65000, Total: 65000, Status: 'READY' },
      { Item_id: 203, Item_name: 'Chả Giò Hoa Sen Giòn', Quantity: 1, Price: 55000, Total: 55000, Status: 'READY' },
    ],
  },
  {
    Order_id: 105,
    Order_code: 'CHAY-SHIP-112',
    Delivery_platform: 'GrabFood',
    Customer_name: 'Anh Minh',
    Customer_phone: '0918882233',
    Delivery_address: '124 Hoàng Văn Thụ, P.9, Phú Nhuận',
    Total_amount: 155000,
    Final_amount: 155000,
    Status: 'READY',
    Payment_status: 'PAID',
    Payment_type: 'TRANSFER',
    Staff_name: 'Thu Ngân Quầy',
    Created_at: new Date(Date.now() - 15 * 60000).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }),
    items: [
      { Item_id: 301, Item_name: 'Cơm Chiên Dương Châu Chay', Quantity: 2, Price: 50000, Total: 100000, Status: 'READY' },
      { Item_id: 203, Item_name: 'Chả Giò Hoa Sen Giòn', Quantity: 1, Price: 55000, Total: 55000, Status: 'READY' },
    ],
  },
];

export const INITIAL_SYSTEM_SETTINGS: SystemSettings = {
  serverUrl: 'http://localhost:3000',
  brandName: 'Nhà Hàng Chay Hoa Sen',
  hotline: '0901234567',
  address: '123 Đường Hoa Sen, TP. Hồ Chí Minh',
  bankName: 'Techcombank',
  bankAccount: '',
  bankOwner: '',
  soundAlertsEnabled: true,
  sound_enabled: true,

  // Printer & Bill
  printer: 'LAN',
  printerIp: '192.168.1.200:9100',
  paperSize: '80mm',
  autoPrintKitchen: true,
  autoPrintPayment: true,
  resName: 'Nhà Hàng Chay Hoa Sen',
  resAddr: '123 Đường Hoa Sen, TP. Hồ Chí Minh',
  resPhone: '0901234567',
  resWifi: 'Wifi: ChayHoaSen / Pass: 88888888',
  billFooter: 'Kính chúc Quý Khách An Lạc & An Nhiên!\nXin cảm ơn & Hẹn gặp lại Quý Khách!',
  showQrCode: true,
  qrMode: 'VIETQR',
  qrBank: 'TCB',
  qrAccountNo: '',
  qrAccountName: '',

  // Kitchen Sound
  kitchenSoundEnabled: true,
  kitchenSoundType: 'kitchen_bell',
  kitchenSoundVolume: 100,
  kitchenRepeatCount: 3,
  kitchenRepeatInterval: 2,

  // Ready Orders Sound
  readySoundEnabled: true,
  readySoundType: 'dingdong',
  readySoundVolume: 100,
  readyRepeatCount: 5,
  readyRepeatInterval: 1,

  // User Permissions Map
  user_permissions: {
    boi: ['TABLES_VIEW', 'MENU_CARDS', 'CART', 'READY_ORDERS', 'ORDERS_LIST', 'COLLECT_PAYMENT', 'ORDERS_PERSONAL'],
    quay: ['TABLES_VIEW', 'ORDERS_LIST', 'ORDERS_ALL', 'COLLECT_PAYMENT', 'REPORTS_STATS', 'MENU_CARDS', 'CART', 'READY_ORDERS', 'ORDERS_PERSONAL'],
    bep: ['KITCHEN', 'READY_ORDERS', 'ORDERS_PERSONAL'],
  },
};
