CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    Detail_id INTEGER PRIMARY KEY AUTOINCREMENT,
    Order_id INTEGER NOT NULL,
    Item_name TEXT NOT NULL,
    Quantity INTEGER NOT NULL DEFAULT 1,
    Unit_price REAL NOT NULL DEFAULT 0,
    Total_price REAL NOT NULL DEFAULT 0,
    FOREIGN KEY (Order_id) REFERENCES ORDERS(Order_id) ON DELETE CASCADE
);