name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Build & Package IPA
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          npm ci || npm install
          npx expo prebuild --platform ios --clean
          
          cd ios
          # Tắt sandbox & code signing trực tiếp vào Podfile
          sed -i '' 's/post_install do |installer|/post_install do |installer|\
            installer.pods_project.targets.each { |t| t.build_configurations.each { |c| c.build_settings["CODE_SIGNING_ALLOWED"] = "NO"; c.build_settings["ENABLE_USER_SCRIPT_SANDBOXING"] = "NO" } }/g' Podfile
          
          pod install
          
          # Biên dịch và nén IPA
          xcodebuild build -workspace ReactFood.xcworkspace -scheme ReactFood -configuration Release -destination "generic/platform=iOS" -derivedDataPath build CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY=""
          mkdir -p Payload && cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r -y ReactFood.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: ReactFood-IPA
          path: ios/ReactFood.ipa
